version: '3'

services:
  ansible-gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      GATEWAY_REMOTE_HOST:
      #GATEWAY_USE_ROUTER:
    volumes:
      - "config_volume:/config"
      - "data_volume:/data"
volumes:
  config_volume:
  data_volume:
